// General
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const TOGGLE_BACK = 'TOGGLE_BACK'
export const IS_BACK_VISIBLE = 'IS_BACK_VISIBLE'
export const SET_SUBTITLE = 'SET_SUBTITLE'
export const IS_WORLD_VISIBLE = 'IS_WORLD_VISIBLE'
export const SET_HOME_BAR = 'SET_HOME_BAR'
export const SET_OTHER_BAR = 'SET_OTHER_BAR'
export const SET_DETAIL_BAR = 'SET_DETAIL_BAR'
export const SET_IS_LOGGED = 'SET_IS_LOGGED'
export const SET_ADDMOVIESTAR = 'SET_ADDMOVIESTAR'
export const SET_ALREADYSTARRED = 'SET_ALREADYSTARRED'

export const SET_MESSAGE = 'SET_MESSAGE'

// User
export const ADD_USER_BEGIN = 'ADD_USER_BEGIN'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE'
export const ADD_MOVIE_BEGIN = 'ADD_MOVIE_BEGIN'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE'
export const SET_ISLOADING = 'SET_ISLOADING'
