// General
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const TOGGLE_BACK = 'TOGGLE_BACK';
export const IS_BACK_VISIBLE = 'IS_BACK_VISIBLE';
export const SET_SUBTITLE = 'SET_SUBTITLE';
export const IS_WORLD_VISIBLE = 'IS_WORLD_VISIBLE';
export const SET_HOME_BAR = 'SET_HOME_BAR';
export const SET_OTHER_BAR = 'SET_OTHER_BAR';
export const SET_DETAIL_BAR = 'SET_DETAIL_BAR';
export const SET_IS_LOGGED = 'SET_IS_LOGGED';
export const SET_ADDMOVIESTAR = 'SET_ADDMOVIESTAR';
export const SET_ALREADYSTARRED = 'SET_ALREADYSTARRED';
export const REFRESH = 'REFRESH';
export const TOGGLE_NEXT = 'TOGGLE_NEXT';
export const TOGGLE_SUGGEST = 'TOGGLE_SUGGEST';
export const SET_ALREADYNEXT = 'SET_ALREADYNEXT';
export const SET_PAGENAME = 'SET_PAGENAME';
export const SET_MESSAGE = 'SET_MESSAGE';

// User
export const ADD_USER_BEGIN = 'ADD_USER_BEGIN';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_MOVIE_BEGIN = 'ADD_MOVIE_BEGIN';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_SERIE_SUCCESS = 'ADD_SERIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';
export const ADD_NEXT_SUCCESS = 'ADD_NEXT_SUCCESS';
export const ADD_TIP_SUCCESS = 'ADD_TIP_SUCCESS';
export const REMOVE_MOVIE_SUCCESS = 'REMOVE_MOVIE_SUCCESS';
export const REMOVE_SERIE_SUCCESS = 'REMOVE_SERIE_SUCCESS';
export const REMOVE_NEXT_SUCCESS = 'REMOVE_NEXT_SUCCESS';
export const REMOVE_TIP_SUCCESS = 'REMOVE_TIP_SUCCESS';
export const REMOVE_TIP_VIEWED_SUCCESS = 'REMOVE_TIP_VIEWED_SUCCESS';
export const SET_ISLOADING = 'SET_ISLOADING';
